"""add user ownership to directories

Revision ID: c853f595255e
Revises: fa7accc7b71b
Create Date: 2026-07-13 17:34:41.960655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c853f595255e'
down_revision: Union[str, Sequence[str], None] = 'fa7accc7b71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NEW
    # Step 1: Add the column as nullable because existing rows already exist.
    op.add_column(
        "directories",
        sa.Column("user_id", sa.Integer(), nullable=True),
    )

    # NEW
    # Step 2: Existing directories belong to the only existing user.
    op.execute(
        "UPDATE directories SET user_id = 1"
    )

    # NEW
    # Step 3: Make the column mandatory.
    op.alter_column(
        "directories",
        "user_id",
        nullable=False,
    )

    # NEW
    # Step 4: Enforce referential integrity.
    op.create_foreign_key(
        "fk_directories_user_id_users",
        "directories",
        "users",
        ["user_id"],
        ["id"],
    )
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('todos', 'due_date',
    #            existing_type=sa.DATE(),
    #            nullable=True)
    # op.alter_column('todos', 'description',
    #            existing_type=sa.String(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    op.drop_constraint(
    "fk_directories_user_id_users",
    "directories",
    type_="foreignkey",
    )
    op.drop_column('directories', 'user_id')
    # ### end Alembic commands ###
